<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120127112255 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_author (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, homepage VARCHAR(255) DEFAULT NULL, createdat DATETIME DEFAULT NULL, updatedat VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_conflictlink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_2179AF53BF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_package (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, repository VARCHAR(255) DEFAULT NULL, createdat DATETIME DEFAULT NULL, updatedat DATETIME DEFAULT NULL, crawledat DATETIME DEFAULT NULL, indexedat DATETIME DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_providelink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_811E0D89BF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_recommendlink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_633C8802BF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_replacelink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_ACE8F045BF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_requirelink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_2302515FBF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_suggestlink (flow3_persistence_identifier VARCHAR(40) NOT NULL, version VARCHAR(40) DEFAULT NULL, packagename VARCHAR(255) DEFAULT NULL, packageversion VARCHAR(255) DEFAULT NULL, INDEX IDX_751A0539BF1CD3C3 (version), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_tag (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_version (flow3_persistence_identifier VARCHAR(40) NOT NULL, package VARCHAR(40) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, targetdir VARCHAR(255) DEFAULT NULL, extra LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', homepage VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, normalizedversion VARCHAR(255) DEFAULT NULL, development TINYINT(1) DEFAULT NULL, license LONGTEXT NOT NULL, source LONGTEXT DEFAULT NULL, dist LONGTEXT DEFAULT NULL, autoload LONGTEXT DEFAULT NULL, binaries LONGTEXT DEFAULT NULL, createdat DATETIME DEFAULT NULL, updatedat DATETIME DEFAULT NULL, releasedat DATETIME DEFAULT NULL, INDEX IDX_60A67D4EDE686795 (package), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_version_tags_join (artifactserver_version VARCHAR(40) NOT NULL, artifactserver_tag VARCHAR(40) NOT NULL, INDEX IDX_C5164E598BD7786 (artifactserver_version), INDEX IDX_C5164E58896CF38 (artifactserver_tag), PRIMARY KEY(artifactserver_version, artifactserver_tag)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_artifactserver_domain_model_version_authors_join (artifactserver_version VARCHAR(40) NOT NULL, artifactserver_author VARCHAR(40) NOT NULL, INDEX IDX_7C58469F98BD7786 (artifactserver_version), INDEX IDX_7C58469F1E4A37B9 (artifactserver_author), PRIMARY KEY(artifactserver_version, artifactserver_author)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_conflictlink ADD CONSTRAINT FK_2179AF53BF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_providelink ADD CONSTRAINT FK_811E0D89BF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_recommendlink ADD CONSTRAINT FK_633C8802BF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_replacelink ADD CONSTRAINT FK_ACE8F045BF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_requirelink ADD CONSTRAINT FK_2302515FBF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_suggestlink ADD CONSTRAINT FK_751A0539BF1CD3C3 FOREIGN KEY (version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version ADD CONSTRAINT FK_60A67D4EDE686795 FOREIGN KEY (package) REFERENCES typo3_artifactserver_domain_model_package(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_tags_join ADD CONSTRAINT FK_C5164E598BD7786 FOREIGN KEY (artifactserver_version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_tags_join ADD CONSTRAINT FK_C5164E58896CF38 FOREIGN KEY (artifactserver_tag) REFERENCES typo3_artifactserver_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_authors_join ADD CONSTRAINT FK_7C58469F98BD7786 FOREIGN KEY (artifactserver_version) REFERENCES typo3_artifactserver_domain_model_version(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_authors_join ADD CONSTRAINT FK_7C58469F1E4A37B9 FOREIGN KEY (artifactserver_author) REFERENCES typo3_artifactserver_domain_model_author(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_authors_join DROP FOREIGN KEY FK_7C58469F1E4A37B9");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version DROP FOREIGN KEY FK_60A67D4EDE686795");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_tags_join DROP FOREIGN KEY FK_C5164E58896CF38");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_conflictlink DROP FOREIGN KEY FK_2179AF53BF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_providelink DROP FOREIGN KEY FK_811E0D89BF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_recommendlink DROP FOREIGN KEY FK_633C8802BF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_replacelink DROP FOREIGN KEY FK_ACE8F045BF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_requirelink DROP FOREIGN KEY FK_2302515FBF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_suggestlink DROP FOREIGN KEY FK_751A0539BF1CD3C3");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_tags_join DROP FOREIGN KEY FK_C5164E598BD7786");
		$this->addSql("ALTER TABLE typo3_artifactserver_domain_model_version_authors_join DROP FOREIGN KEY FK_7C58469F98BD7786");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_author");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_conflictlink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_package");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_providelink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_recommendlink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_replacelink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_requirelink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_suggestlink");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_tag");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_version");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_version_tags_join");
		$this->addSql("DROP TABLE typo3_artifactserver_domain_model_version_authors_join");
	}
}

?>